### PR TITLE
Impr/theme change

### PR DESCRIPTION
**Pull request by alexsandertech**
image

### CODE REVIEW

**Review by lucassanttoss — APPROVED** [review]
Go!

**Review by robertolima-dev — COMMENTED** [review]
OK

**Review by robertolima-dev — COMMENTED** [review]
OK

**Review by robertolima-dev — COMMENTED** [review]
OK

**Review by robertolima-dev — APPROVED** [review]
Approved!

**Review by robertolima-dev — COMMENTED** [review]
OK

**Pull request merged**
